language: node_js
node_js:
- '6'
branches:
  only:
  - master
  - develop
notifications:
  email:
    on_failure: always
install: true
deploy:
  provider: npm
  email: npm@lukechavers.com
  on:
    repo: vmadman/node-common
  api_key:
    secure: Ut5p02611pqSUVd+RcUNlRruTR96RBjQ/OWkMKtCqF0WMMKcc21PBHKwXbW8rIt0F1f5poANrubK+YkJVzw+jMERwsdIw4KKIRdemyFQTnrIJaF/ZWeGnRSepyYG9ysq0mYLeUVRj126ej1OrQ+NOreOf+YOpTpSdFJ7cH2Q19zNNr8YrM56Jg8lylCnXSWrYOiicLlnRaccqktgp0FRKhUyDn5oyNMacIj2tFyrXuPHV+2W6gnB37DwpzKtMxPHBKJGzR6dCDN/aYioUb+K6A7yPU0j5k2uTQ+qnfDPsj+o78BdTtmKo9Nv/uJ2xXYNWvp31ygcIMvlyMa8sCknxE6lNk5UfJV4X5+3hoPuTt4MvOJ7njPnlPCg3QPAu3EReDtfMZXvUhlQiz/5dS+A68c6ldZ4mGXVHLctv0kmGTMbLBRn0ztbFwTFEudcqv/nVZAOBgZxqud1Fa+EWKCr3icZ1Y+oTvQOW7ORaszzzBZmashTcxtoMN7JXLDYopCQPIc9K808T8jnN/luj/8+V7ZNsyH0DNdD7UYTsa1xMTRIM7t5p4dTn7XD2wuA2Cv4/HZWLJbfns9yTILz4c/DPQLA8M30dWIw8876an8j4BLBzLXm3b0VSy1whRC6eHJ9sNwefYvqqTJW5qIozwxAsI6u3zwJejLRHUX+cD59qb0=
